
GUARD_VOLTEDGE_TERRAIN :?= false
.if (!GUARD_VOLTEDGE_TERRAIN)
  GUARD_VOLTEDGE_TERRAIN := true

  VoltEdge_Terrain_Created = 0.02
  VoltEdge_Terrain_Updated = 0.15

  ; Created: 0.15
  ; Updated: 0.15
  ; Terrain constants

    TerrainMapEdge     = $00
    TerrainPeak        = $01
    TerrainThicket     = $02
    TerrainCliff       = $03
    TerrainPlains      = $04
    TerrainForest      = $05
    TerrainSea         = $06
    TerrainRiver       = $07
    TerrainMountain    = $08
    TerrainSandyLand   = $09
    TerrainCastle      = $0A
    TerrainFort        = $0B
    TerrainHouse1      = $0C
    TerrainGate        = $0D
    TerrainUnknown1    = $0E
    TerrainWasteland   = $0F
    TerrainBridge      = $10
    TerrainLake        = $11
    TerrainVillage     = $12
    TerrainRuins       = $13
    TerrainUnknown2    = $14
    TerrainUnknown3    = $15
    TerrainConvoy      = $16
    TerrainChurch1     = $17
    TerrainHouse2      = $18
    TerrainRoad        = $19
    TerrainArmory      = $1A
    TerrainVendor      = $1B
    TerrainArena       = $1C
    TerrainFloor       = $1D
    TerrainUnknown4    = $1E
    TerrainThrone      = $1F
    TerrainDoor        = $20
    TerrainChest1      = $21
    TerrainExit        = $22
    TerrainPillar      = $23
    TerrainDrawbridge  = $24
    TerrainSecretShop  = $25
    TerrainUnknown5    = $26
    TerrainSandySoil   = $27
    TerrainMagicFloor1 = $28
    TerrainMagicFloor2 = $29
    TerrainChurch2     = $2A
    TerrainChest2      = $2B

  ; Terrain macros

  ; Created: 0.02
  ; Updated: 0.07
  structTerrainEntry .struct MapEdge=?, Peak=?, Thicket=?, Cliff=?, Plains=?, Forest=?, Sea=?, River=?, Mountain=?, SandyLand=?, Castle=?, Fort=?, House1=?, Gate=?, Unknown1=?, Wasteland=?, Bridge=?, Lake=?, Village=?, Ruins=?, Unknown2=?, Unknown3=?, Convoy=?, Church1=?, House2=?, Road=?, Armory=?, Vendor=?, Arena=?, Floor=?, Unknown4=?, Throne=?, Door=?, Chest1=?, Exit=?, Pillar=?, Drawbridge=?, SecretShop=?, Unknown5=?, SandySoil=?, MagicFloor1=?, MagicFloor2=?, Church2=?, Chest2=?
    MapEdge     .char \MapEdge
    Peak        .char \Peak
    Thicket     .char \Thicket
    Cliff       .char \Cliff
    Plains      .char \Plains
    Forest      .char \Forest
    Sea         .char \Sea
    River       .char \River
    Mountain    .char \Mountain
    SandyLand   .char \SandyLand
    Castle      .char \Castle
    Fort        .char \Fort
    House1      .char \House1
    Gate        .char \Gate
    Unknown1    .char \Unknown1
    Wasteland   .char \Wasteland
    Bridge      .char \Bridge
    Lake        .char \Lake
    Village     .char \Village
    Ruins       .char \Ruins
    Unknown2    .char \Unknown2
    Unknown3    .char \Unknown3
    Convoy      .char \Convoy
    Church1     .char \Church1
    House2      .char \House2
    Road        .char \Road
    Armory      .char \Armory
    Vendor      .char \Vendor
    Arena       .char \Arena
    Floor       .char \Floor
    Unknown4    .char \Unknown4
    Throne      .char \Throne
    Door        .char \Door
    Chest1      .char \Chest1
    Exit        .char \Exit
    Pillar      .char \Pillar
    Drawbridge  .char \Drawbridge
    SecretShop  .char \SecretShop
    Unknown5    .char \Unknown5
    SandySoil   .char \SandySoil
    MagicFloor1 .char \MagicFloor1
    MagicFloor2 .char \MagicFloor2
    Church2     .char \Church2
    Chest2      .char \Chest2
  .endstruct

.endif ; GUARD_VOLTEDGE_TERRAIN
