
GUARD_VOLTEDGE_TERRAIN :?= false
.if (!GUARD_VOLTEDGE_TERRAIN)
  GUARD_VOLTEDGE_TERRAIN := true

  VoltEdge_Terrain_Created = 0.02
  VoltEdge_Terrain_Updated = 0.21

  ; Created: 0.15
  ; Updated: 0.19
  ; Terrain constants

    TerrainMapEdge           = $00
    TerrainPeak              = $01
    TerrainThicket           = $02
    TerrainCliff             = $03
    TerrainPlains            = $04
    TerrainForest            = $05
    TerrainSea               = $06
    TerrainRiver             = $07
    TerrainMountain          = $08
    TerrainSand              = $09
    TerrainCastle            = $0A
    TerrainFort              = $0B
    TerrainHouse             = $0C
    TerrainGate              = $0D
    TerrainOutdoorImpassable = $0E
    TerrainWasteland         = $0F
    TerrainBridge            = $10
    TerrainLake              = $11
    TerrainVillage           = $12
    TerrainRuins             = $13
    TerrainUnknown2          = $14
    TerrainRoof              = $15
    TerrainSupply            = $16
    TerrainChurch            = $17
    TerrainClosedHouse       = $18
    TerrainRoad              = $19
    TerrainArmory            = $1A
    TerrainVendor            = $1B
    TerrainArena             = $1C
    TerrainFloor             = $1D
    TerrainIndoorImpassable  = $1E
    TerrainThrone            = $1F
    TerrainDoor              = $20
    TerrainIndoorChest       = $21
    TerrainExit              = $22
    TerrainPillar            = $23
    TerrainDrawbridge        = $24
    TerrainSecretShop        = $25
    TerrainBreakableWall     = $26
    TerrainSandySoil         = $27
    TerrainMagicFloor        = $28
    TerrainMagicFloorCenter  = $29
    TerrainClosedChurch      = $2A
    TerrainOutdoorChest      = $2B

  ; Terrain macros

  ; Created: 0.02
  ; Updated: 0.21
  structTerrainEntry .struct MapEdge=?, Peak=?, Thicket=?, Cliff=?, Plains=?, Forest=?, Sea=?, River=?, Mountain=?, Sand=?, Castle=?, Fort=?, House=?, Gate=?, OutdoorImpassable=?, Wasteland=?, Bridge=?, Lake=?, Village=?, Ruins=?, Unknown2=?, Roof=?, Supply=?, Church=?, ClosedHouse=?, Road=?, Armory=?, Vendor=?, Arena=?, Floor=?, IndoorImpassable=?, Throne=?, Door=?, IndoorChest=?, Exit=?, Pillar=?, Drawbridge=?, SecretShop=?, BreakableWall=?, SandySoil=?, MagicFloor=?, MagicFloorCenter=?, ClosedChurch=?, OutdoorChest=?
    MapEdge           .char \MapEdge
    Peak              .char \Peak
    Thicket           .char \Thicket
    Cliff             .char \Cliff
    Plains            .char \Plains
    Forest            .char \Forest
    Sea               .char \Sea
    River             .char \River
    Mountain          .char \Mountain
    Sand              .char \Sand
    Castle            .char \Castle
    Fort              .char \Fort
    House             .char \House
    Gate              .char \Gate
    OutdoorImpassable .char \OutdoorImpassable
    Wasteland         .char \Wasteland
    Bridge            .char \Bridge
    Lake              .char \Lake
    Village           .char \Village
    Ruins             .char \Ruins
    Unknown2          .char \Unknown2
    Roof              .char \Roof
    Supply            .char \Supply
    Church            .char \Church
    ClosedHouse       .char \ClosedHouse
    Road              .char \Road
    Armory            .char \Armory
    Vendor            .char \Vendor
    Arena             .char \Arena
    Floor             .char \Floor
    IndoorImpassable  .char \IndoorImpassable
    Throne            .char \Throne
    Door              .char \Door
    IndoorChest       .char \IndoorChest
    Exit              .char \Exit
    Pillar            .char \Pillar
    Drawbridge        .char \Drawbridge
    SecretShop        .char \SecretShop
    BreakableWall     .char \BreakableWall
    SandySoil         .char \SandySoil
    MagicFloor        .char \MagicFloor
    MagicFloorCenter  .char \MagicFloorCenter
    ClosedChurch      .char \ClosedChurch
    OutdoorChest      .char \OutdoorChest
  .endstruct

.endif ; GUARD_VOLTEDGE_TERRAIN
